logging:
  level:
    org.springframework: INFO
    org.springframework.data.r2dbc: DEBUG,
    io.rsocket: DEBUG
  file:
    path: ./logs/${spring.application.name}
server:
  port: 9900
spring:
  webflux:
    date-format: "yyyy-MM-dd HH:mm:ss"
  rsocket:
    server:
      port: 9901
      transport: websocket
      mapping-path: /rsocket
  application:
    name: rsocket-playboard-server
  r2dbc:
    name: rsocket-playboard-db-${spring.profiles.active}
    username: h2
    password: 123123
    url: r2dbc:h2:mem:///playboard-db?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    pool:
      initial-size: 5
      max-size: 500
      validation-query: SELECT 1 FROM DUAL
  jackson:
    locale: zh_CN
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    database: 0
    host: 127.0.0.0
    port: 16379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 3000
        max-idle: 10
        max-wait: 5000
        min-idle: 3
        time-between-eviction-runs: 5000