logging:
  level:
    org.springframework: INFO
  file:
    path: ./logs/${spring.application.name}
server:
  port: 8080
spring:
  webflux:
    date-format: "yyyy-MM-dd HH:mm:ss"
  rsocket:
    server:
      port: 9090
      transport: websocket
      mapping-path: /rsocket
  application:
    name: rsocket-playboard-server
  datasource:
    name: rsocket-playboard-db-${spring.profiles.active}
    username: h2
    password: 123123
    type: org.h2.jdbcx.JdbcDataSource
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:playboard-db
    hikari:
      connection-test-query: select 1 FROM DUAL
      connection-timeout: 10000
      idle-timeout: 30000
      max-lifetime: 60000
      maximum-pool-size: 1000
      minimum-idle: 5
      validation-timeout: 5000
  jackson:
    locale: zh_CN
    time-zone: "Asia/Shanghai"
    date-format: "yyyy-MM-dd HH:mm:ss"
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    database: 0
    host: 127.0.0.0
    port: 16379
    password:
    timeout: 5000
    lettuce:
      pool:
        max-active: 3000
        max-idle: 10
        max-wait: 5000
        min-idle: 3
        time-between-eviction-runs: 5000